workflows:
  swift-ci-workflow:
    name: TourKSA Pipeline
    scripts:
      - name: CI/CD Started
        script: echo "Welcome to your CI/CD setup for TourKSA 🎉"
      - name: Build TourKSA
        script: |
          xcodebuild build \
          -workspace "TourKsa_Swe.xcodeproj" \
          -scheme "TourKsa_Swe" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - khalidald4z@gmail.com  # Replace with your email to receive the build report
