workflows:
  ios-spm-workflow:
    name: iOS SPM Build and Test
    environment:
      xcode: 15.2  # Ensure you select the correct Xcode version
    scripts:
      - name: Resolve Swift Package Dependencies
        script: xcodebuild -resolvePackageDependencies -project "TourKsa_Swe.xcodeproj"
      - name: Build TourKSA
        script: xcodebuild build -project "TourKsa_Swe.xcodeproj" -scheme "TourKsa_Swe" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Run Unit Tests
        script: |
          xcodebuild test \
            -project "TourKsa_Swe.xcodeproj" \
            -scheme "TourKsa_Swe" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult
    artifacts:
      - build/**
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/**
      - TestResults.xcresult
    publishing:
      email:
        recipients:
          - khalidald4z@gmail.com
        notify:
          success: true
          failure: true
